language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update

install: 
  - sudo apt-get install debhelper autotools-dev dh-autoreconf

before_script:
  - ./buildconf && ./configure

script:
  - make
