# Copyright (C) The c-ares project and its contributors
# SPDX-License-Identifier: MIT
name: clang-format check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - include
          - src
    steps:
      - uses: actions/checkout@v3
      - uses: jidicula/clang-format-action@v4.11.0
        with:
          check-path: ${{ matrix.path }}
          clang-format-version: "17"
