# Copyright (C) The c-ares project and its contributors
# SPDX-License-Identifier: MIT
name: DJGPP
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubutu-latest
    env:
      WATT_ROOT: "${{ github.workspace }}/watt-32"
      DJGPP_PREFIX: "${{ github.workspace }}/djgpp/bin/i586-pc-msdosdjgpp"
      DJ_PREFIX: "${{ github.workspace }}/djgpp/bin/i586-pc-msdosdjgpp"
    steps:
      - name: Checkout c-ares
        uses: actions/checkout@v4
      - name: Checkout Watt-32
        uses: actions/checkout@v4
        with:
          repository: gvanem/Watt-32
          path: watt-32
      - name: Fetch DJGPP
        run: |
          wget https://github.com/andrewwutw/build-djgpp/releases/download/v3.4/djgpp-linux64-gcc1220.tar.bz2
          tar -jxpf djgpp-linux64-gcc1220.tar.bz2
      - name: Build Watt-32
        run: |
          cd watt-32/src
          ./configur.sh djgpp
          echo "Configured"
          make -f djgpp.mak
      - name: Build c-ares
        run: |
          cp include/ares_build.h.dist include/ares_build.h
          make -f Makefile.dj



