# Copyright (C) The c-ares project and its contributors
# SPDX-License-Identifier: MIT
name: DJGPP
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    env:
      WATT_ROOT: "${{ github.workspace }}\\watt-32"
      DJGPP_PREFIX: "${{ github.workspace }}\\djgpp\\bin\\i586-pc-msdosdjgpp"
      DJ_PREFIX: "${{ github.workspace }}\\djgpp\\bin\\i586-pc-msdosdjgpp"
    steps:
      - name: Install mingw-w64-make
        uses: msys2/setup-msys2@v2
        with:
          install: mingw-w64-x86_64-make
      - name: show files
        shell: msys2 {0}
        run: |
          cd /msys64
          ls -lR
      - name: dir msys
        run: |
          dir c:\msys64
      - name: dir msys mingw64
        run: |
          dir c:\msys64\mingw64
      - name: dir msys mingw64 bin
        run: |
          dir c:\msys64\mingw64\bin
      - name: Checkout c-ares
        uses: actions/checkout@v4
      - name: Checkout Watt-32
        uses: actions/checkout@v4
        with:
          repository: gvanem/Watt-32
          path: watt-32
      - name: Fetch DJGPP
        run: |
          Invoke-WebRequest https://github.com/andrewwutw/build-djgpp/releases/download/v3.4/djgpp-mingw-gcc1220-standalone.zip -OutFile djgpp-mingw-gcc1220-standalone.zip
          Expand-Archive -Path djgpp-mingw-gcc1220-standalone.zip
      - name: Build Watt-32
        run: |
          cd watt-32\src
          & .\configur.bat djgpp
          echo "Configured"
          c:\msys64\usr\bin\make -f djgpp.mak
        # Powershell doesn't preserve environment variables set by configur.bat
        env:
          MKMAKE: ..\util\win32\mkmake.exe
          MKDEP: ..\util\win32\mkdep.exe
          HC_ERR: ..\util\win32\hc_err.exe
          WC_ERR: ..\util\win32\wc_err.exe
          BCC_ERR: ..\util\win32\bcc_err.exe
          W32_BIN2C: ..\util\win32\bin2c.exe
          W32_BIN2C_: ../util/win32/bin2c.exe
          W32_NASM: ..\util\win32\nasm.exe
          W32_NASM_: ../util/win32/nasm.exe
          DJ_ERR: ..\util\win32\dj_err.exe
      - name: Build c-ares
        run: |
          Copy-Item "include\ares_build.h.dist" -Destination "include\ares_build.h"
          c:\msys64\usr\bin\make -f Makefile.dj



