# Copyright (C) The c-ares project and its contributors
# SPDX-License-Identifier: MIT
name: Solaris

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Solaris Build and Test"
    env:
      DIST: SOLARIS
      BUILD_TYPE: "cmake"
      CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=DEBUG -DCARES_STATIC=ON -DCARES_STATIC_PIC=ON -DCMAKE_VERBOSE_MAKEFILE=ON"
      CMAKE_TEST_FLAGS: "-DCMAKE_PREFIX_PATH=/usr/local/ -DCARES_BUILD_TESTS=ON"
      TEST_FILTER: "--gtest_filter=-*LiveSearchTXT*:*LiveSearchANY*"
    steps:
      - uses: actions/checkout@v4
      - name: Solaris Build and Test
        id: solaris
        uses: vmactions/solaris-vm@v1
        with:
          envs: 'DIST BUILD_TYPE CMAKE_FLAGS CMAKE_TEST_FLAGS TEST_FILTER'
          usesh: true
          # package list: http://pkg.oracle.com/solaris/release/en/catalog.shtml
          prepare: |
            pkg install -v --no-refresh cmake gcc pkg-config gnu-make git
          # Note: using googletest v1.13.x because that's the last version to support cmake 3.9, v1.14.x went to cmake 3.13
          run: |
            git clone --depth=1 -b v1.13.x https://github.com/google/googletest googletest
            cd googletest
            cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_GMOCK=ON -DINSTALL_GTEST=ON -DGTEST_HAS_PTHREAD=0 .
            gmake
            gmake install
            cd ..
            ./ci/build.sh
            ./ci/test.sh
