# Copyright (C) The c-ares project and its contributors
# SPDX-License-Identifier: MIT
name: WATT32
on:
  push:
    branches:
      - watt32
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build c-ares
        run: |
          Copy-Item "include\ares_build.h.dist" -Destination "include\ares_build.h"
          nmake /NOLOGO /f .\Makefile.msvc



